### ISSUE TITLE
分页功能好像不行

### ISSUE THREAD

**Issue by LLawlight** [laobubu/jekyll-theme-EasyBook#1]
一直说page2 not found.请问大神怎么回事？要怎么解决啊？TAT

**Comment by laobubu** [comment]
表示我[搭建在 GitHub 上的博客](http://blog.laobubu.net/)分页功能还是正常的。

请问能否提供你的repo地址 或者 运行环境？

**Comment by LLawlight** [comment]
> 请问能否提供你的repo地址 或者 运行环境？

http://clark-zhao.github.io/jekyll-theme-EasyBook-gh-pages/
我现在直接将您的主题下载下来然后传上去，显示的页面无样式。
由于我晚上换了一台主机，我的分页情况暂时无法提供给您。
具体就是，我创建8篇博客，按照您的设置，有三篇应该出现在第二页，但是我点了下一页，显示not found。我的cmd里面提示的是page2 not found。但是我看到_site里面已经自动创建page2了。然后我把项目上传到github，连第一页的文章都不显示了。
@laobubu

**Comment by laobubu** [comment]
格式消失是因为你没有修改 `_config.yml` 中的 `url` 和 `baseurl` 参数。对于 http://clark-zhao.github.io/jekyll-theme-EasyBook-gh-pages/ ，应该这样

``` yaml
url: "http://clark-zhao.github.io"
baseurl: "/jekyll-theme-EasyBook-gh-pages"
```

至于第二个问题……你再上传那些文章试一试吧…

**Comment by LLawlight** [comment]
http://clark-zhao.github.io/blogger/
分页分好了，点下一页就404
@laobubu

**Comment by laobubu** [comment]
好吧，确实是一个 bug，现在应该已经可以用了。

感谢测试与报告这个问题。

**Comment by LLawlight** [comment]
我非常喜欢您的主题，同时非常感谢您的耐心。谢谢！
