### ISSUE TITLE
行内公式不能正确解析。

### ISSUE THREAD

**Issue by liweiwei1419** [laobubu/jekyll-theme-EasyBook#13]
您好 @laobubu ，很喜欢您的博客模板，但是试用以后，发现行内公式不能正确解析，不知道还要做哪些设置，特向您请教一下，谢谢！
![370f4b95-1c04-42f7-8b4a-4addbe48e1d1](https://user-images.githubusercontent.com/7555554/39415153-75222f18-4c72-11e8-87a3-6ce16a978a4f.png)

**Comment by liweiwei1419** [comment]
我按照您的示例文章找到解决办法了，就是使用 `$$ O(n^2) $$` 语法。

**Comment by laobubu** [comment]
Jekyll 的 Markdown 解析器必须用两个美元符号，这个没办法，凑合使了 ¯\_(ツ)_/¯
