### ISSUE TITLE
page 预览文章

### ISSUE THREAD

**Issue by myselfghost** [laobubu/jekyll-theme-EasyBook#4]
请问一下，在浏览文章列表 时候，每个文章的预览有的多有的少，是怎么回事？怎么样让文章预览不要太多？

**Comment by laobubu** [comment]
默认情况下，取第一个空行前面的内容。

你也可以指定摘要取到哪里为止，在 YAML Front matter 里添加 excerpt_separator 字段即可。

例子:
https://raw.githubusercontent.com/laobubu/laobubu.blog/gh-pages/_posts/2016-02-18-web-richedit-empty-line.md
2016年4月21日 下午5:52，"ArtEngr" notifications@github.com写道：

**Comment by myselfghost** [comment]
谢谢啊

**Comment by KrisYu** [comment]
发现这个link很有用：

https://gist.github.com/mikeygee/2626538

针对中文

    {{ post.content | truncatewords: 5 }}

这样预览效果也还不错

**Comment by laobubu** [comment]
@KrisYu 看起来不错，应该可以和 `excerpt_separator` 一起使用。等什么时候修改修改主题
